jasypt:
  encryptor:
    password: 666

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/secret?characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: ENC(SrpFBcVD89eTQ2icOD0TMg==)
    driver-class-name: com.mysql.jdbc.Driver

file:
    path: E:\repository\com\weasel\secret\common\secret-common\1.0-SNAPSHOT