spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/secret?characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 5805703
    driver-class-name: com.mysql.jdbc.Driver