jasypt:
  encryptor:
    password: 666

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/secret?characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: ENC(SrpFBcVD89eTQ2icOD0TMg==)
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

file:
    path: D:\apks
    url: http://127.0.0.1:3330/download

logging:
  level:
     root: info
     org:
       springframework: warn
       hibernate: warn
       eclipse: warn
       apache: warn
  file: "logs/application.log"
